# Generated by Django 3.2 on 2023-05-13 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='chatrooms.room'),
            preserve_default=False,
        ),
    ]
