# Generated by Django 3.2 on 2023-05-13 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0006_customuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='chatrooms.room'),
        ),
    ]
