# Generated by Django 3.2 on 2023-05-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0010_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=False, upload_to='post'),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default=False, upload_to='room'),
        ),
    ]
