# Generated by Django 3.2 on 2023-05-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0011_auto_20230516_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=False, upload_to='post'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, default=False, upload_to='room'),
        ),
        migrations.AddConstraint(
            model_name='connect',
            constraint=models.UniqueConstraint(fields=('follow', 'follower'), name='connect_unique'),
        ),
    ]
