# Generated by Django 3.2 on 2023-05-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0013_auto_20230519_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(blank=True, default=False, upload_to='icon'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='icon_changed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
