# Generated by Django 3.2 on 2023-05-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0016_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='kind',
            field=models.IntegerField(choices=[(0, 'system notice'), (1, 'the user followed you'), (2, 'received the message'), (3, 'the user replied you')], default=0),
        ),
    ]
