# Generated by Django 3.2 on 2023-05-24 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0017_notice_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='send_from',
        ),
        migrations.RemoveField(
            model_name='message',
            name='send_to',
        ),
        migrations.AddField(
            model_name='message',
            name='cansel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='received',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_message', to='chatrooms.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='sent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_message', to='chatrooms.customuser'),
            preserve_default=False,
        ),
    ]
