# Generated by Django 3.2 on 2023-05-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0018_auto_20230524_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, default=False, upload_to='messasge'),
        ),
    ]
