# Generated by Django 3.2 on 2023-05-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0020_rename_cansel_message_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='message_only_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='config',
            name='notice_only_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notice',
            name='kind',
            field=models.IntegerField(choices=[(0, 'system notice'), (1, 'important or fatal notice in system notice'), (2, 'notice from other users')], default=0),
        ),
    ]
