# Generated by Django 3.2 on 2023-05-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0021_auto_20230527_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='friend',
            field=models.IntegerField(choices=[(0, '全体に公開する'), (1, 'フレンドのみ公開'), (2, '非公開')], default=0),
        ),
        migrations.AddField(
            model_name='config',
            name='room_post_log',
            field=models.IntegerField(choices=[(0, '全体に公開する'), (1, 'フレンドのみ公開'), (2, '非公開')], default=0),
        ),
    ]
