# Generated by Django 3.2 on 2023-05-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0022_auto_20230529_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_address',
            field=models.EmailField(default='notset@example.com', max_length=254),
        ),
    ]
