# Generated by Django 3.2 on 2023-05-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0023_customuser_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='message_only_connected',
        ),
        migrations.RemoveField(
            model_name='config',
            name='notice_only_connected',
        ),
        migrations.AddField(
            model_name='config',
            name='message',
            field=models.IntegerField(choices=[(0, '全員に許可する'), (1, 'フレンドのみ許可'), (2, '全員から受け取らない')], default=0),
        ),
        migrations.AddField(
            model_name='config',
            name='notice',
            field=models.IntegerField(choices=[(0, '全員に許可する'), (1, 'フレンドのみ許可'), (2, '全員から受け取らない')], default=0),
        ),
    ]
